// export { default as vestalPortrait } from "./heroes/vestal.webp";
// export { default as plagueDoctorPortrait } from "./heroes/plague-doctor.webp";
// export { default as crusaderPortrait } from "./heroes/crusader.webp";
// export { default as graveRobberPortrait } from "./heroes/grave-robber.webp";
// export { default as leperPortrait } from "./heroes/leper.webp";
// export { default as highwaymanPortrait } from "./heroes/highwayman.webp";
export { default as vestalPortrait } from "./heroes/vestal_portrait_roster.png";
export { default as plagueDoctorPortrait } from "./heroes/plague_doctor_portrait_roster.png";
export { default as crusaderPortrait } from "./heroes/crusader_portrait_roster.png";
export { default as graveRobberPortrait } from "./heroes/grave_robber_portrait_roster.png";
export { default as leperPortrait } from "./heroes/leper_portrait_roster.png";
export { default as highwaymanPortrait } from "./heroes/highwayman_portrait_roster.png";
